
POSTGRE_HOST = '127.0.0.1'
POSTGRE_PORT = '5432'
POSTGRE_USER = 'admin'
POSTGRE_PASSWORD = '1234'
POSTGRE_DATABASE = 'aiohttp_sample'
POSTGRE_DSN = f'postgres://{POSTGRE_USER}:{POSTGRE_PASSWORD}@{POSTGRE_HOST}:{POSTGRE_PORT}/{POSTGRE_DATABASE}'

